Repository go-vela/ui, pull requests merged in 2019-12, with the labels that each got.

#41 feat(pager): add paging for builds/hooks
  cypress/fixtures/builds_10a.json
  cypress/fixtures/builds_10b.json
  cypress/fixtures/hooks_10a.json
  cypress/fixtures/hooks_10b.json
  cypress/integration/build.spec.js
  cypress/integration/builds.spec.js
  cypress/integration/hooks.spec.js
  cypress/support/commands.js
  src/elm/Api.elm
  src/elm/Build.elm
  src/elm/Crumbs.elm
  src/elm/Main.elm
  src/elm/Pager.elm
  src/elm/Pages.elm
  src/elm/Pages/Hooks.elm
  src/elm/Routes.elm
  src/elm/SvgBuilder.elm
  src/elm/Vela.elm
  src/scss/style.scss
Labels: feature

#44 feat: add changelog for releases
  .chglog/CHANGELOG.tpl.md
  .chglog/config.yml
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  .github/workflows/release.yml
Labels: feature

#48 build(node): bump node to latest LTS
  .github/workflows/ci.yml
  .github/workflows/release.yml
  .nvmrc
  package-lock.json
  package.json
Labels: dependencies

#47 improvement(pager): allow custom prev/next labels
  src/elm/Main.elm
  src/elm/Pager.elm
Labels: enhancement

#49 feat(logs): linking to log lines via URL fragments
  cypress/integration/build.spec.js
  cypress/integration/builds.spec.js
  cypress/integration/steps.spec.js
  cypress/support/commands.js
  src/elm/Build.elm
  src/elm/Crumbs.elm
  src/elm/Main.elm
  src/elm/Pages.elm
  src/elm/Pages/Hooks.elm
  src/elm/Routes.elm
  src/elm/SvgBuilder.elm
  src/elm/Vela.elm
  src/scss/_variables.scss
  src/scss/style.scss
Labels: feature

#50 fix(alerts): forcing animated class into post-compile
  src/elm/Alerts.elm
  src/scss/style.scss
Labels: bug

#57 fix: update add repo to default server timeout
  cypress/fixtures/add_repo_response.json
  cypress/fixtures/overview_page.json
  cypress/fixtures/repositories.json
  cypress/fixtures/repositories_100.json
  cypress/fixtures/repositories_5.json
  cypress/fixtures/repository.json
  cypress/fixtures/repository_bad.json
  cypress/fixtures/source_repos.json
  cypress/integration/settings.spec.js
  docker-compose.yml
  nginx/local.conf
  src/elm/Vela.elm
Labels: bug
