Repository go-vela/ui, pull requests merged in 2020-12, with the labels that each got.

#240 feat(repo settings): allow minimum build timeout of 1 minute
  src/elm/Pages/RepoSettings.elm
Labels: feature

#241 fix(html): simplify logs header code
  src/elm/Pages/Build/View.elm
  src/scss/_main.scss
Labels: enhancement

#227 feat(secret): add delete button
  cypress/fixtures/secret_org.json
  cypress/integration/secrets.spec.js
  src/elm/Api.elm
  src/elm/Main.elm
  src/elm/Pages/Secrets/Form.elm
  src/elm/Pages/Secrets/Model.elm
  src/elm/Pages/Secrets/Update.elm
  src/elm/Pages/Secrets/View.elm
  src/scss/_main.scss
Labels: feature

#243 chore(elm): reorganize msg
  src/elm/Main.elm
Labels: enhancement

#247 fix(logs): log line resource in url not setting focus
  src/elm/Focus.elm
Labels: bug
