Repository go-vela/ui, pull requests merged in 2020-05, with the labels that each got.

#146 feat(secrets): pages for managing repo, org and shared secrets
  elm.json
  src/elm/Api.elm
  src/elm/Api/Endpoint.elm
  src/elm/Help/Help.elm
  src/elm/Main.elm
  src/elm/Nav.elm
  src/elm/Pages/Home.elm
  src/elm/Pages/Hooks.elm
  src/elm/Pages/Secrets/Form.elm
  src/elm/Pages/Secrets/Model.elm
  src/elm/Pages/Secrets/Update.elm
  src/elm/Pages/Secrets/View.elm
  src/elm/Table/Table.elm
  src/elm/Util.elm
  src/elm/Vela.elm
  src/scss/_forms.scss
  src/scss/_main.scss
Labels: feature

#157 enhancement(secrets): add comment event
  src/elm/Pages/Secrets/Form.elm
Labels: enhancement

#164 docs: divert bugs and features to community
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/not_here.md
  .github/README.md
Labels: enhancement

#166 fix(refresh): refresh page when returning to an inactive tab
  src/elm/Main.elm
Labels: bug

#168 revert: repo issue template
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/not_here.md
Labels: enhancement
