Repository go-vela/ui, pull requests merged in 2020-01, with the labels that each got.

#65 fix(history): avoid pushurl to login
  cypress/integration/auth.spec.js
  cypress/integration/builds.spec.js
  src/elm/Main.elm
Labels: bug

#64 refactor(addrepos): renaming add to enable/moving it to settings page
  cypress/integration/add_repositories.spec.js
  cypress/integration/overview.spec.js
  cypress/integration/searching.spec.js
  cypress/integration/settings.spec.js
  src/elm/Api.elm
  src/elm/Main.elm
  src/elm/Pages/AddRepos.elm
  src/elm/Pages/Home.elm
  src/elm/Pages/Settings.elm
  src/elm/Vela.elm
  src/scss/_main.scss
Labels: enhancement

#69 docs(typo): use correct word
  .github/DOCS.md
Labels: enhancement

#70 chore(deps): bump node/npm
  .github/workflows/ci.yml
  .github/workflows/release.yml
  .nvmrc
  package.json
Labels: dependencies

#73 chore: update copyright for 2020
  .editorconfig
  .github/README.md
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  .github/workflows/release.yml
  .postcssrc.js
  .prettierrc.js
  .stylelintrc.js
  cypress/integration/add_repositories.spec.js
  cypress/integration/auth.spec.js
  cypress/integration/crumbs.spec.js
  cypress/integration/errors.spec.js
  cypress/integration/hooks.spec.js
  cypress/integration/overview.spec.js
  cypress/integration/settings.spec.js
  src/elm/Alerts.elm
  src/elm/Api.elm
  src/elm/Api/Endpoint.elm
  src/elm/Api/Header.elm
  src/elm/Api/Pagination.elm
  src/elm/Build.elm
  src/elm/Crumbs.elm
  src/elm/Errors.elm
  src/elm/Interop.elm
  src/elm/Main.elm
  src/elm/Main/index.d.ts
  src/elm/Pager.elm
  src/elm/Pages.elm
  src/elm/Pages/AddRepos.elm
  src/elm/Pages/Home.elm
  src/elm/Pages/Hooks.elm
  src/elm/Pages/Settings.elm
  src/elm/Routes.elm
  src/elm/Search.elm
  src/elm/SvgBuilder.elm
  src/elm/Util.elm
  src/elm/Vela.elm
  src/scss/_animations.scss
  src/scss/_main.scss
  src/scss/_mixins.scss
  src/scss/_reset.scss
  src/scss/_themes.scss
  src/scss/_variables.scss
  src/scss/style.scss
  src/static/index.ts
Labels: enhancement

#75 feat(favorites): user favorites
  LICENSE
  cypress/fixtures/favorites.json
  cypress/fixtures/favorites_add.json
  cypress/fixtures/favorites_none.json
  cypress/integration/a11y.spec.js
  cypress/integration/add_repositories.spec.js
  cypress/integration/errors.spec.js
  cypress/integration/favorites.spec.js
  cypress/integration/overview.spec.js
  cypress/integration/settings.spec.js
  cypress/integration/steps.spec.js
  cypress/integration/theme.spec.js
  docker-compose.yml
  package-lock.json
  src/elm/Api.elm
  src/elm/Api/Endpoint.elm
  src/elm/Favorites.elm
  src/elm/Main.elm
  src/elm/Pages/AddRepos.elm
  src/elm/Pages/Home.elm
  src/elm/Pages/Settings.elm
  src/elm/Search.elm
  src/elm/SvgBuilder.elm
  src/elm/Util.elm
  src/elm/Vela.elm
  src/scss/_main.scss
Labels: feature

#74 refactor(css): separate and normalize button css
  .stylelintrc.js
  cypress/integration/add_repositories.spec.js
  cypress/integration/favorites.spec.js
  src/elm/Favorites.elm
  src/elm/Main.elm
  src/elm/Pager.elm
  src/elm/Pages/AddRepos.elm
  src/elm/Pages/Home.elm
  src/elm/Pages/Settings.elm
  src/elm/SvgBuilder.elm
  src/scss/_buttons.scss
  src/scss/_main.scss
  src/scss/_mixins.scss
  src/scss/_themes.scss
  src/scss/style.scss
Labels: enhancement

#77 chore(deps): update dependencies
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  .github/workflows/release.yml
  package-lock.json
  package.json
Labels: dependencies

#79 perf(server): use visibility to control automatic server fetching
  src/elm/Main.elm
Labels: enhancement
