Repository go-vela/ui, pull requests merged in 2020-02, with the labels that each got.

#82 feat(home): home/overview search bar
  cypress/integration/overview.spec.js
  src/elm/Main.elm
  src/elm/Pages/AddRepos.elm
  src/elm/Pages/Home.elm
  src/elm/Pages/Settings.elm
  src/elm/Search.elm
  src/elm/Vela.elm
  src/scss/_main.scss
  src/scss/_themes.scss
Labels: feature

#83 fix(nav): nav module and hooks page nav fix
  src/elm/Main.elm
  src/elm/Nav.elm
Labels: bug, enhancement

#84 perf(html): lazy node rendering for pages root
  src/elm/Logs.elm
  src/elm/Main.elm
  src/elm/Pages/AddRepos.elm
  src/elm/Pages/Build.elm
  src/elm/Pages/Home.elm
  src/elm/Pages/Hooks.elm
Labels: enhancement

#85 refactor(css): forms related control refactor
  cypress/integration/add_repositories.spec.js
  cypress/integration/settings.spec.js
  cypress/integration/steps.spec.js
  cypress/support/commands.js
  src/elm/Main.elm
  src/elm/Pages/AddRepos.elm
  src/elm/Pages/Build.elm
  src/elm/Pages/Home.elm
  src/elm/Pages/Hooks.elm
  src/elm/Pages/Settings.elm
  src/elm/Search.elm
  src/elm/SvgBuilder.elm
  src/scss/_buttons.scss
  src/scss/_details.scss
  src/scss/_forms.scss
  src/scss/_main.scss
  src/scss/_mixins.scss
  src/scss/_settings.scss
  src/scss/_themes.scss
  src/scss/style.scss
Labels: enhancement

#86 fix(star): use standard line width for stroke
  src/scss/_main.scss
Labels: enhancement

#87 refactor(html): ensure content is in landmarks
  src/elm/Main.elm
  src/scss/_main.scss
Labels: enhancement

#101 feat(filter): ability to filter builds by event
  cypress/fixtures/builds_all.json
  cypress/fixtures/builds_pull.json
  cypress/fixtures/builds_push.json
  cypress/fixtures/builds_tag.json
  cypress/integration/build.spec.js
  cypress/integration/builds.spec.js
  cypress/integration/contextual_help.spec.js
  cypress/support/commands.js
  src/elm/Api.elm
  src/elm/Api/Endpoint.elm
  src/elm/Crumbs.elm
  src/elm/Help/Commands.elm
  src/elm/Help/Help.elm
  src/elm/Main.elm
  src/elm/Nav.elm
  src/elm/Pages.elm
  src/elm/Pages/AddRepos.elm
  src/elm/Pages/Build.elm
  src/elm/Pages/Builds.elm
  src/elm/Pages/Home.elm
  src/elm/Routes.elm
  src/elm/Vela.elm
  src/scss/_main.scss
Labels: feature

#111 chore(deps): update dependencies
  package-lock.json
  package.json
Labels: dependencies

#110 feat(build): dynamic build status favicons
  package-lock.json
  package.json
  src/elm/Interop.elm
  src/elm/Main.elm
  src/elm/Main/index.d.ts
  src/elm/Vela.elm
  src/static/images/favicon-failure.ico
  src/static/images/favicon-pending.ico
  src/static/images/favicon-running.ico
  src/static/images/favicon-success.ico
  src/static/index.ts
Labels: feature

#112 fix(filter): change pull -> pull_request
  cypress/fixtures/builds_pull.json
  cypress/integration/builds.spec.js
  src/elm/Main.elm
  src/elm/Pages/Build.elm
  src/scss/_main.scss
Labels: bug

#115 feat(settings): add chown/repair actions
  cypress/integration/settings.spec.js
  package-lock.json
  src/elm/Api.elm
  src/elm/Api/Endpoint.elm
  src/elm/Main.elm
  src/elm/Pages/Settings.elm
  src/elm/Vela.elm
  src/scss/_settings.scss
Labels: feature

#116 feat(settings): add status badge section
  cypress/integration/settings.spec.js
  src/elm/Alerts.elm
  src/elm/Help/Help.elm
  src/elm/Main.elm
  src/elm/Pages/Settings.elm
  src/elm/Vela.elm
  src/scss/_main.scss
Labels: feature

#117 fix(csp): allow svg from server
  nginx/default.conf
  nginx/local.conf
Labels: bug
