Repository go-vela/ui, pull requests merged in 2021-01, with the labels that each got.

#255 refactor(steps): update log test cypress attributes, prep work
  cypress/integration/logs.spec.js
  cypress/integration/steps.spec.js
  src/elm/Pages/Build/View.elm
Labels: enhancement

#257 feat(nav): adding pipeline types and download yml button, prep work
  src/elm/Api.elm
  src/elm/Main.elm
  src/elm/Pages/Pipeline/Api.elm
  src/elm/Pages/Pipeline/Model.elm
  src/elm/Pages/Pipeline/Update.elm
  src/elm/Pages/Pipeline/View.elm
  src/elm/Vela.elm
  src/scss/_pipelines.scss
Labels: enhancement

#256 refactor(steps): adding StepsModel and moving code from Update.elm, prep work
  src/elm/Main.elm
  src/elm/Pages/Build/Logs.elm
  src/elm/Pages/Build/Model.elm
  src/elm/Pages/Build/Update.elm
  src/elm/Pages/Build/View.elm
  src/elm/Vela.elm
Labels: enhancement

#286 feat(nav): implement BuildPipeline and build tab navigation
  cypress/fixtures/logs_services_ansi.json
  cypress/fixtures/services_5.json
  cypress/integration/crumbs.spec.js
  cypress/integration/logs.spec.js
  cypress/integration/steps.spec.js
  cypress/support/commands.js
  src/elm/Crumbs.elm
  src/elm/Help/Commands.elm
  src/elm/Main.elm
  src/elm/Nav.elm
  src/elm/Pages.elm
  src/elm/Pages/Build/History.elm
  src/elm/Pages/Build/Model.elm
  src/elm/Pages/Build/View.elm
  src/elm/Pages/Pipeline/Model.elm
  src/elm/Routes.elm
  src/elm/Vela.elm
  src/scss/_main.scss
  src/scss/_nav.scss
Labels: feature

#239 feat(auth): deal with expiring token
  cypress/fixtures/auth.json
  cypress/fixtures/sessionstorage.json
  cypress/integration/add_repositories.spec.js
  cypress/integration/auth.spec.js
  cypress/integration/builds.spec.js
  cypress/integration/contextual_help.spec.js
  cypress/integration/crumbs.spec.js
  cypress/integration/favorites.spec.js
  cypress/integration/settings.spec.js
  cypress/integration/steps.spec.js
  cypress/support/commands.js
  docker-compose.yml
  src/elm/Api.elm
  src/elm/Api/Endpoint.elm
  src/elm/Auth/Jwt.elm
  src/elm/Auth/Session.elm
  src/elm/Crumbs.elm
  src/elm/Help/Commands.elm
  src/elm/Interop.elm
  src/elm/Main.elm
  src/elm/Main/index.d.ts
  src/elm/Pages.elm
  src/elm/Pages/Pipeline/Model.elm
  src/elm/Pages/Secrets/Model.elm
  src/elm/Pages/Settings.elm
  src/elm/Vela.elm
  src/static/index.ts
Labels: feature

#301 fix: error rendering on hooks page
  src/elm/Pages/Hooks.elm
  src/scss/_table.scss
  src/scss/_themes.scss
Labels: bug

#304 feat: add visual alert for audit
  src/elm/Nav.elm
  src/scss/_nav.scss
Labels: feature
