Repository go-vela/ui, pull requests merged in 2021-05, with the labels that each got.

#403 fix: update github spelling
  src/elm/Main.elm
  src/elm/Pages/SourceRepos.elm
Labels: enhancement

#405 fix(form): fix overlap in non-stack scenario
  src/scss/_forms.scss
Labels: bug

#404 feat: update build counter to settings page
  cypress/fixtures/enable_repo_response.json
  cypress/fixtures/overview_page.json
  cypress/fixtures/repositories.json
  cypress/fixtures/repositories_100.json
  cypress/fixtures/repositories_5.json
  cypress/fixtures/repository.json
  cypress/fixtures/repository_bad.json
  cypress/fixtures/repository_inactive.json
  cypress/fixtures/repository_updated.json
  cypress/fixtures/source_repos.json
  cypress/integration/repo_settings.spec.js
  src/elm/Main.elm
  src/elm/Pages/RepoSettings.elm
  src/elm/Vela.elm
Labels: feature
